name: deploy website
on: [push, pull_request]
jobs:

  Speedcurv Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Post request to speedcurv
      run: |
        curl --request POST \
            --url https://api.speedcurve.com/v1/deploys \
            --header 'accept: application/json' \
            --header 'authorization: Basic MW9uYzlzbTFlanJ3bzl4aHE0ODV2OTJjd2c0b2FuOng=' \
            --header 'cache-control: no-cache' \
            --header 'content-type: application/json' \
            --data '{"site_id" : "745662","url_id": "3916716","note" : "github test","detail" : "Testing 10 details"}'